# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mahdi Torabi Rad
title: Research Associate (Deep Learning)
email: mtorabirad@gmail.com
phone: 015159106815
website: mtorabirad.github.io

# Social links
github_username:  mtorabirad
linkedin_username: mtorabirad


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a computational scientist and self-trained software developer with +10 years of experience 
  in developing mathematical models and computer codes to simulate phenomena in physics. 
  My expertise is in quantitative modeling; solving complex problems by breaking them into their fundamental elements; 
  and communicating complicated information in an easy-to-understand, clear, and concise manner. 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Honors & Awards
more_content: | 
  - to be completed.
  


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
