# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Dr. Mahdi Torabi Rad
title: Data Scientist / Machine Learning Engineer
email: mtorabirad@gmail.com
phone: +1 647 4936057
website: mtorabirad.github.io

# Social links
github_username:  mtorabirad
linkedin_username: mtorabirad


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a computational scientist and self-trained software developer experienced in developing mathematical models 
  and computer code to simulate phenomena in physics. My expertise is in quantitative modeling; solving complex problems 
  by breaking them into their fundamental elements; and communicating complicated information in an easy-to-understand, clear, and concise manner. 

# More Section
more_title: Skills
more_content: | 
  - **Programming Languages**: Python, C++, MATLAB, Go, Scala 
  -	**Python Libraries**: SciPy, NumPy, Pandas, Matplotlib, Jupyter
  -	**Naturel Language Processing (NLP)**: NLTK, Gensim, Spacy
  -	**Deep Learning Frameworks**: TensorFlow, PyTorch, Keras
  -	**Computer Vision**: CUDA, OpenCV
  -	**Data Engineering**: SQL, Scrappy
  -	**Big Data and Cloud Technologies**: Spark, AWS

more_title_2: DEEP LEARNING INVITED TALKS/PUBLICATIONS
more_content_2: | 
  - M. Torabi Rad, (Feb. 2, 2021). Theory-training neural networks.  **NVIDIA SimNet Seminars (Invited)**. 
  - M. Torabi Rad et al., (2020). Theory-training deep neural networks for an alloy solidification benchmark problem. Computational Materials Science, 180, 109687.
  - M. Torabi Rad et al., (2020). On theory-training neural networks to infer the solution of highly coupled differential equations. Under Review in Computer Methods in Applied Mechanics and Engineering.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
